### ISSUE TITLE
Use stable schema identifiers to generate comparable files

### ISSUE THREAD

**Issue by saily** [ePages-de/restdocs-api-spec#128]
I'm currently using `restdocs-api-spec==0.9.7` to generate `openapi3.yaml` file from a Spring Boot application. I'm looking for a way to compare the new and the previously generated file - ideally using my favorite diff tool. 

**From**: *The currently generated identifier with a random number*

```yaml
components:
  schemas:
    services-template-id49180138:  # <=== identifier + random number
      type: object
      properties:
        # ...
    labels-id-318250730:  # <=== identifier + random number
      type: object
      properties:
        # ...
```

After digging in the codebase (please consider my minimal Kotlin skills) it seems `schema.hashCode()`  in the method [generateSchemaName](https://github.com/ePages-de/restdocs-api-spec/blob/0.9.7/restdocs-api-spec-openapi3-generator/src/main/kotlin/com/epages/restdocs/apispec/openapi3/OpenApi3Generator.kt#L156) is appended to the `identifier`. Seems #126 has addressed this or a similar problem - but I'm missing the docs how to use it.

**To**: *more meaningful and stable identifiers*

```yaml
components:
  schemas:
    ServiceTemplate:  # <=== stable identifier
      type: object
      properties:
        # ...
    Label:  # <=== stable identifier
      type: object
      properties:
        # ...
```

Is it possible to customize this behavior so I can generate files which have more meaningful identifier for schemas?
