### ISSUE TITLE
FieldDescriptor optional() is not working

### ISSUE THREAD

**Issue by traeper** [ePages-de/restdocs-api-spec#172]
Hello. 
I'm gratefully use restdocs-api-spec in my company.

Overall, it seems that the API specification is well generated. However, even if the FieldDescriptor entering the requestFields/responseFields is written to perform optional(), the generated yml file does not display the optional value.

Could you please tell me how to display the nullable value in requestFields/responseFields

Thanks in advance.

**Comment by traeper** [comment]
I found ConstrainedFields that may fix my issue.
Thanks. :D

**Comment by ozscheyge** [comment]
Hey!

`optional()` should work even for regular FieldDescriptors. Which target format are you generating?

**Comment by traeper** [comment]
I want to generate 'nullable' property.

API RequestBody data object has nullable value. (metadata)



* mockMvc test code
```kotlin
mockMvc.perform(
            post("/api/v1/test")
                .param("transaction_id", transactionId)
                .contentType(MediaType.APPLICATION_JSON)
                .content(json)
        )
            .andExpect(status().isOk)
            .andExpect(content().contentType(MediaType.APPLICATION_JSON))
            .andDo(
                MockMvcRestDocumentationWrapper.document(
                    "test/{methodName}",
                    requestParameters(requestParameterDescriptors()),
                    requestFields(requestFieldDescriptors()),
                    responseFields(responseFieldDescriptors())
                )
            )
```

* private descriptors codes
```kotlin
    private fun requestParameterDescriptors(): List<ParameterDescriptor> = listOf(
        parameterWithName("transaction_id").description("transaction id")
    )

    private fun requestFieldDescriptors(): List<FieldDescriptor> =
        listOf(
            fieldWithPath("number1").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("number2").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("type").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("content").type(JsonFieldType.STRING).description("desc"),
            fieldWithPath("metadata").type(JsonFieldType.STRING).description("desc").optional(),
        )

    private fun responseFieldDescriptors(): List<FieldDescriptor> = listOf(
        fieldWithPath("transaction_id").type(JsonFieldType.STRING)
            .description("transaction id")
    )
```


the result of yml file is below. 
metadata is not optional (I need to generate nullable or required)

```yaml
    api-v1-test-hmac793873085:
      type: object
      properties:
        metadata:
          type: string
          description: desc
        number2:
          type: string
          description: desc
        number1:
          type: string
          description: desc
        type:
          type: string
          description: desc
        content:
          type: string
          description: desc
```
