### ISSUE TITLE
default value in ParameterDescriptor

### ISSUE THREAD

**Issue by jgazeau** [ePages-de/restdocs-api-spec#187]
Hello,

It doesn't seems possible to manage a default value for `ParameterDescriptor` when generating OpenAPI.
For example having something like:
```yaml
        - name: stringParameter
          in: query
          description: a string parameter
          required: false
          schema:
            type: string
            default: a default value
```
![image](https://user-images.githubusercontent.com/45284640/130655219-c16f5fd1-3db6-46b0-b1d5-1f505dbbb871.png)

I've created a PR to solve it. If you can have a look at it, it would be great.
Regards,

Jordan.
