### ISSUE TITLE
optional() is not working in OpenAPI 3

### ISSUE THREAD

**Issue by tabuyos** [ePages-de/restdocs-api-spec#213]
First of all thank you very much for your contribution on rest docs.

Here is my debug screenshot

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/45193148/203340023-64e7c7c1-ff70-455e-9f46-d3d37b4295fa.png">

and section of `resource.json`

```json
"requestFields" : [ {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "username",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "password",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "confirmPw",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "tel",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "email",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "idCard",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "realName",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "nickname",
      "type" : "STRING",
      "optional" : false
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "avatar",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "gender",
      "type" : "NUMBER",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "areaId",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "typeId",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "address",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "houseNumber",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "homeMaster",
      "type" : "STRING",
      "optional" : true
    }, {
      "attributes" : { },
      "description" : "",
      "ignored" : false,
      "path" : "homeMasterId",
      "type" : "STRING",
      "optional" : true
    } ]
```

and section of `openapi3.yaml`

```yaml
    UserSignUpMessage:
      title: UserSignUpMessage
      type: object
      properties:
        address: {type: string, description:}
        gender: {type: number, description:}
        idCard: {type: string, description: }
        homeMaster: {type: string, description: }
        houseNumber: {type: string, description: }
        avatar: {type: string, description: }
        realName: {type: string, description:}
        password: {type: string, description:}
        areaId: {type: string, description:}
        confirmPw: {type: string, description:}
        nickname: {type: string, description:}
        typeId: {type: string, description:}
        tel: {type: string, description:}
        homeMasterId: {type: string, description:}
        email: {type: string, description:}
        username: {type: string, description: }
```

Each section is relatively complete, I have read #90 #172 that It doesn't seem to help me much. I'm not sure if I'm missing something, or doing something stupid

:)
