### ISSUE TITLE
Do not aggregate FieldDescriptors for different content types

### ISSUE THREAD

**Issue by mduesterhoeft** [ePages-de/restdocs-api-spec#26]
When aggregating FieldDescriptors for different requests with the same path and method we now always aggregate the FieldDescriptors from all requests and create a JsonSchema. In case we have requests/response for different content types we should not do this.

A good example is `PATCH` `/products/{id}` in the sample app - here we have two requests with `application/json-patch+json` and `application/json` and we currently generate this schema:

```yaml
type: "object"
    required:
    - "name"
    - "price"
    properties:
      '[]':
        type: "object"
        properties:
          path:
            type: "string"
            description: "The path of the field."
          op:
            type: "string"
            description: "Patch operation."
          value:
            type: "string"
            description: "The value to assign."
      price:
        type: "number"
        description: "The price of the product."
      name:
        type: "string"
        description: "The name of the product."
        minLength: 1
```

This is obviously wrong.
