### ISSUE TITLE
How to specify format of the field?

### ISSUE THREAD

**Issue by mgwoj** [ePages-de/restdocs-api-spec#76]
In the specification it is possible to add to the field of type `string`, that its format it `date` or `date+time`. For example
```
                   entryTime:
                      type: string
                      format: date-time
                      description: time of entry
 
```

How to achieve that with this plugin?
